name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:

  #  BUILD JOB
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean compile

  #  TEST JOB
  test:
    runs-on: ubuntu-latest
    needs: build   # runs AFTER build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          cd backend
          mvn test

  #  DEPLOY JOB
  deploy:
    runs-on: ubuntu-latest
    needs: test   # runs AFTER test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
